reader:
    image: kishori82/dev:COLAS3
    command: /home/docker/COLAS/src/abdprocess --process-type 0
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib:/home/docker/COLAS/src/abd:/home/docker/COLAS/src/soda:/home/docker/COLAS/src/codes
    volumes:
      - /home/docker:/home/docker

        #writer:
        #    image: kishori82/dev:COLAS3
        #    command: /home/docker/COLAS/src/abdprocess --process-type 1
        #    volumes:
        #      - /home/docker:/home/docker
        #    environment:
        #      - LD_LIBRARY_PATH=/usr/local/lib:/home/docker/COLAS/src/abd:/home/docker/COLAS/src/soda:/home/docker/COLAS/src/codes
        #
        #server:
        #    image: kishori82/dev:COLAS3
        #    command: /home/docker/COLAS/src/abdprocess --process-type 2 --init-file-size 1
        #    volumes:
        #      - /home/docker:/home/docker
        #    environment:
        #      - LD_LIBRARY_PATH=/usr/local/lib:/home/docker/COLAS/src/abd:/home/docker/COLAS/src/soda:/home/docker/COLAS/src/codes
        #
        #controller:
        #    image: kishori82/dev:COLAS3
        #    command: /home/docker/COLAS/src/abdprocess --process-type 3
        #    volumes:
        #      - /home/docker:/home/docker
        #    environment:
        #      - LD_LIBRARY_PATH=/usr/local/lib:/home/docker/COLAS/src/abd:/home/docker/COLAS/src/soda:/home/docker/COLAS/src/codes
