reader:
    image: kishori82/dev:COLAS3
    command: /home/docker/COLAS/src/abdprocess --process-type 0
    environment:
    - LD_LIBRARY_PATH=/usr/local/lib:/home/docker/COLAS/src/abd:/home/docker/COLAS/src/soda:/home/docker/COLAS/src/codes:/home/docker/COLAS/src/sodaw
    volumes:
     - /home/docker:/home/docker


writer:
    image: kishori82/dev:COLAS3
    command: /home/docker/COLAS/src/abdprocess --process-type 1
    environment:
    - LD_LIBRARY_PATH=/usr/local/lib:/home/docker/COLAS/src/abd:/home/docker/COLAS/src/soda:/home/docker/COLAS/src/codes:/home/docker/COLAS/src/sodaw
    volumes:
     - /home/docker:/home/docker

server:
    image: kishori82/dev:COLAS3
    command: /home/docker/COLAS/src/abdprocess --process-type 2 --init-file-size 1000
    environment:
    - LD_LIBRARY_PATH=/usr/local/lib:/home/docker/COLAS/src/abd:/home/docker/COLAS/src/soda:/home/docker/COLAS/src/codes:/home/docker/COLAS/src/sodaw
    volumes:
     - /home/docker:/home/docker

controller:
    image: kishori82/dev:COLAS3
    command: /home/docker/COLAS/src/abdprocess --process-type 3
    environment:
    - LD_LIBRARY_PATH=/usr/local/lib:/home/docker/COLAS/src/abd:/home/docker/COLAS/src/soda:/home/docker/COLAS/src/codes:/home/docker/COLAS/src/sodaw
    volumes:
     - /home/docker:/home/docker
